require 'minitest/autorun'
# require_relative '../app/factories/command_factory'
# require_relative '../app/models/place_command'
# require_relative '../app/models/move_command'
# require_relative '../app/models/left_command'
# require_relative '../app/models/right_command'
# require_relative '../app/models/report_command'
require_relative '../app/models/table'
require_relative '../app/models/robot'
require_relative '../app/models/position'
